version: 2
jobs:
  build:
    working_directory: ~/chatapp-zuul
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: chatapp-zuul-{{checksum "pom.xml"}}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: chatapp-zuul-{{checksum "pom.xml"}}
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/chatapp-zuul-1.0.1-RELEASE.jar
      - run:
          name: Install sonarqube
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
            unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - run: - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
          name: Run Sonarqube scanner
          command: |
            mvn sonar:sonar
            -Dsonar.projectKey=chatapp-zuul
            -Dsonar.organization=tommygoossens-github
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${SONARQUBE_TOKEN}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
            mvn clean compile com.google.cloud.tools:jib-maven-plugin:0.9.7:build -Dimage=tommygoossens/chatapp-gateway:release

